question_data = [
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Geography",
            "question": "New Haven is the capital city of the state of Connecticut in the United States.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Geography",
            "question": "Hungary is the only country in the world beginning with H.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Geography",
            "question": "Vatican City is a country.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Geography",
            "question": "St. Louis is the capital of the US State Missouri.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Geography",
            "question": "There is a city called Rome in every continent on Earth.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Geography",
            "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Geography",
            "question": "San Marino is the only country completely surrounded by another country.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Geography",
            "question": "A group of islands is called an &#039;archipelago&#039;.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Geography",
            "question": "Tokyo is the capital of Japan.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Geography",
            "question": "Greenland is almost as big as Africa.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
    ]

